### ISSUE TITLE
Did you find answer?

### ISSUE THREAD

**Issue by pichuser** [juona/mongoose-zonejs#1]
Hello! Thank you very much for your repo! Today I got the same behavior with zone-node+mongoose.. (in Angular application with Server Side Rendering). Have you some solution or  workaround?
Thanx!

**Comment by juona** [comment]
Hello,

Terribly sorry for not replying on time - I did not expect anyone to comment on this repo at all... : ]

Yes, I do have a solution, I'll upload it in a few minutes, you may use it, if it's not too late.

**Comment by juona** [comment]
@pichuser I have uploaded an example workaround with some comments and updated the readme explaining the basic idea.

I too only needed to run Angular Universal (server-side rendering) with ZoneJS and nothing else, so this should work for you.
